config/routes.rb
Rails.application.routes.draw do
  resources :members, only: [:index, :show, :new, :create] do
    resources :friendships, only: [:create]
    collection do
      get :search
    end
    member do
      get :set_current
    end
  end

  get "/pages/:page" => "pages#show"
  root "pages#show", page: :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/member_search.rb
module MemberSearch
  extend ActiveSupport::Concern

  included do
    include PgSearch

    pg_search_scope(
      :search,
      against: %i(html_content)
    )
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord

  belongs_to :member
  belongs_to :friend, class_name: 'Member'

  validates :member_id, uniqueness: {scope: :friend_id}

  def self.are_friends?(user, user_2)
    Friendship.where(member_id: user.id, friend_id: user_2.id).or(Friendship.where(member_id: user_2.id, friend_id: user.id)).any?
  end
end

app/models/member.rb
class Member < ApplicationRecord
  include MemberSearch

  validates :name, :original_website, presence: true
  validates :original_website, url: true, on: :create
  validates :name, uniqueness: true

  after_create :perform_url_shortener

  has_many :friends, class_name: 'Friendship'

  def as_json(options={})
    {
      id: id,
      name: name,
      original_website: original_website,
      website: website
    }
  end

  def friends
    Friendship.where("member_id = ? OR friend_id = ?", self.id, self.id)
  end

  def my_friends
    ids = friends.map{|u| [u.member_id, u.friend_id] }.flatten
    ids -= [self.id]
    Member.find(ids)
  end

  def mutual_friends(user)
    return [] if self == user
    ids = friends.map{|u| [u.member_id, u.friend_id] }.flatten.push(0)
    friend_ids = Friendship.where("member_id in (?) OR friend_id in (?)", ids, ids).map{|u| [u.member_id, u.friend_id] }.flatten

    puts " > > > > > ids : #{ids.inspect}"
    friend_ids -= [self.id, user.id]
    Member.find(friend_ids)
  end

  #######
  private
  #######

  def perform_url_shortener
    UrlShortenerJob.perform_later(self.id)
    PageCrawlJob.perform_later(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Renders
  include MembersHelper
end

app/controllers/concerns/check_pages.rb
module CheckPages
  extend ActiveSupport::Concern

  included do
    before_action :check_for_current_page
  end

  #######
  private
  #######

  def check_for_current_page
    render_not_found and return unless pages_list.include?(params[:page].to_s)
  end

  def pages_list
    @_pages_list ||= Dir.glob(File.join(Rails.root, 'app', 'views', 'pages', '*.*')).map{ |s| File.basename(s, ".html.erb") }
  end

end

app/controllers/concerns/member_sessions.rb
module MemberSessions
  extend ActiveSupport::Concern

  included do
    before_action :require_member
  end

  #######
  private
  #######

  def require_member
    render_unauthorized and return unless current_member
  end

end

app/controllers/concerns/renders.rb
module Renders
  extend ActiveSupport::Concern

  included do
  end

  #######
  private
  #######

  def render_unprocessable(errors)
    respond_to do |format|
      format.html { render(:file => unprocessable_entity_file,  :status => :unprocessable_entity) }
      format.json { render(:json => {:success => false, :error => errors}, status: :unprocessable_entity) }
    end
  end

  def render_unauthorized
    respond_to do |format|
      format.html { render(:file => not_found_file,  :status => :unauthorized) }
      format.json { render(:json=> {:success => false,  :error => "unauthorized"}, :status=>:unauthorized) }
    end
  end

  def render_not_found
    respond_to do |format|
      format.html { render(:file => not_found_file,  :status => :not_found) }
      format.json { render(:json => {:success => false,  :error => "Not Found"}, status: :not_found) }
    end
  end

  def not_found_file
    "#{Rails.root}/public/404.html"
  end

  def unprocessable_entity_file
    "#{Rails.root}/public/422.html"
  end

end

app/controllers/concerns/set_members.rb
module SetMembers
  extend ActiveSupport::Concern

  included do
    before_action :set_member, only: [:show, :new, :set_current]
  end

  #######
  private
  #######

  def set_member
    @member = params[:id].blank? ? Member.new : Member.find(params[:id])
  end

  def member_params
    params.require(:member).permit(:original_website, :name)
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  include MemberSessions
  include SetMembers

  def create
    @friendship = Friendships::CreateService::new(current_member, friend).execute
    respond_to do |format|
      if @friendship && @friendship.persisted?
        format.html { redirect_to friend, notice: 'Friendship was successfully created.' }
        format.json { render :show, status: :created }
      else
        msg = 'Friendship was not created.'
        format.html { redirect_to friend, flash: { :error => msg } }
        format.json { render_unprocessable(msg) }
      end
    end
  end

  #######
  private
  #######

  def friend
    @_friend ||= Member.find(params[:member_id])
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include SetMembers

  def index
    @members = Members::SearchService.new(search_keyword).execute
    @search_keyword = search_keyword
  end

  def search
    @members = Members::MemberSearchService.new(search_keyword).execute
    @search_keyword = search_keyword
  end

  def show
  end

  def new
    # respond to HTML only
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    @member = Members::CreateService.new(member_params).execute
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, member: @member }
      else
        format.html { render :new }
        format.json { render_unprocessable(@member.errors.messages) }
      end
    end
  end

  def set_current
    session["current_member_id"] = @member.id
    respond_to do |format|
      format.html { redirect_to members_path, notice: 'Done successfully.' }
      format.json { render :json => {}, status: :ok }
    end
  end

  #######
  private
  #######

  def search_keyword
    params[:keyword]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include CheckPages

  def show
    render template: "pages/#{params[:page]}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper

  def current_member
    Member.find(session["current_member_id"]) if session["current_member_id"]
  rescue
    session["current_member_id"] = nil
  end

  def can_manage_friendships(friend)
    current_member && current_member != friend
  end

  def can_add_friend(friend)
    !Friendship.are_friends?(current_member, friend)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Friends Website</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/members">Members</a></li>
              <li><a href="#"></a></li>
              <li><a href="#"></a></li>
            </ul>

            <% if current_member %>
              <ul class="nav navbar-nav navbar-right">
                <li class="active">
                  <%= link_to current_member.name, current_member %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>

      <%= render partial: '/shared/messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Name" %>
    <%= form.text_field :name, class: "form-control", "aria-describedby" => "nameHelp",  placeholder: "Name" %>
    <small id="nameHelp" class="form-text text-muted">Member Full Name</small>
  </div>

  <div class="form-group">
    <%= form.label :original_website, "Website" %>
    <%= form.text_field :original_website, class: "form-control", "aria-describedby" => "websiteHelp",  placeholder: "Website" %>
    <small id="websiteHelp" class="form-text text-muted">Member Website</small>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/members/_index.html.erb
<div class = "page-header">
  <h1>
    Members
    <small><%= link_to 'New Member', new_member_path %></small>
  </h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Original website</th>
      <th scope="col">Website</th>
      <th scope="col" colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <th scope="row"><%= member.id %></th>
        <td><%= member.name %></td>
        <td><%= link_to member.original_website, member.original_website, target: "_blank" %></td>
        <td><%= member.website %></td>
        <td><%= link_to 'Set as Current', set_current_member_path(member) %></td>
        <td><%= link_to 'Show', member %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/index.html.erb
<%= render partial: "/shared/search" %>
<%= render "index" %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/search.html.erb
<%= render partial: "/shared/members_search" %>
<%= render "index" %>

app/views/members/show.html.erb
<div class="row profile">
  <div class="col-md-12">
    <div class="profile-sidebar">
      <div class="profile-usertitle">
        <div class="profile-usertitle-name">
          <%= @member.name.upcase %>
        </div>
        <div class="profile-usertitle-name">
          Friends Count : <%= @member.friends.count %>
        </div>
        <div class="profile-usertitle-job">
          <%= link_to "Website", @member.original_website, target: "_blank" %>
        </div>
      </div>

      <% if can_manage_friendships(@member) %>
        <div class="profile-userbuttons">
          <% if can_add_friend(@member) %>
            <%= link_to "Add Friend", member_friendships_path(@member), class: "btn btn-success btn-sm", method: :post %>
          <% else %>
            <a type="button" class="btn btn-danger btn-sm">Remove Friend (Not Implemented)</a>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% my_friends = @member.my_friends %>
<% if my_friends.any? %>
<div class="row profile">
  <div class="col-md-12">
    <div class="profile-sidebar">
      <div class="profile-usermenu">
        <div class="">
          <h3>Friends</h3>
        </div>
        <ul class="nav">
          <li>
            <% @member.my_friends.each do |friend| %>
              <%= link_to friend do %>
                <strong><%= friend.name %></strong>
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<% end %>

<% mutual_friends = current_member.mutual_friends(@member) if current_member %>
<% if mutual_friends && mutual_friends.any? %>
<div class="row profile">
  <div class="col-md-12">
    <div class="profile-sidebar">
      <div class="profile-usermenu">
        <div class="">
          <h1>Mutual Friends</h1>
        </div>
        <ul class="nav">
          <li>
            <% mutual_friends.each do |friend| %>
              <%= link_to friend do %>
                <strong><%= friend.name %></strong>
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome</h1>
  <p>Friendships social network application</p>
  <p>Ruby on Rails</p>
  <p>
    <a class="btn btn-lg btn-primary" href="/members" role="button">Members »</a>
  </p>
</div>

<%= render partial: "/shared/search" %>
<%= render partial: "/shared/members_search" %>

app/views/shared/_members_search.html.erb
<div class="jumbotron">
  <h3>Members Search</h3>
  <%= form_with(model: Member, url: search_members_path, method: :get, local: true) do |form| %>
    <div class="form-group">
      <label for="search_keyword">Member Name</label>
      <input class="form-control" aria-describedby="nameHelp" placeholder="Member Name" type="text" name="keyword" id="search_keyword" value="<%= @search_keyword %>">
      <small id="nameHelp" class="form-text text-muted">Member Name</small>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
  <% end %>
</div>

app/views/shared/_messages.html.erb
<% unless notice.blank? %>
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>
<% end %>

<% unless flash[:error].blank? %>
<div class="alert alert-danger" role="alert">
  <%= flash[:error] %>
</div>
<% end %>

app/views/shared/_search.html.erb
<div class="jumbotron">
  <h3>Search in content by Keyword</h3>
  <%= form_with(model: Member, url: members_path, method: :get, local: true) do |form| %>
    <div class="form-group">
      <label for="search_keyword">Keyword</label>
      <input class="form-control" aria-describedby="nameHelp" placeholder="Keyword" type="text" name="keyword" id="search_keyword" value="<%= @search_keyword %>">
      <small id="nameHelp" class="form-text text-muted">Search Keyword</small>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
  <% end %>
</div>